[project]
name = "Xray_winds"
dependencies = ["numpy", "matplotlib", "starwinds_readplt"]
version = "0.0.6"

[build-system]
requires = ["setuptools>=61.0"]
build-backed = "setuptools.build_meta"
readme = "README.md"
